apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-dev
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:dev
spec:
  project: default
  source:
    repoURL: https://github.com/vladmalynych/devops-edu.git
    path: kargo/argocd/demo-app/demo/environments/dev/manifests.yaml
    targetRevision: stage/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
