apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vladmalynych/devops-edu
    path: kargo/argocd/demo-app/demo/environments/prod
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
    createNamespace: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
