apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-demo-stage
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:stage
spec:
  project: default
  source:
    repoURL: https://github.com/vladmalynych/devops-edu.git
    path: kargo/argocd/demo-app/demo/environments/stage
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-stage
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
