cronjob:
  schedule: '0 10 * * *'
  timeZone: 'UTC'
  suspend: false

image:
  registry: ghcr.io
  repository: renovatebot/renovate
  tag: 38.84.0
  pullPolicy: IfNotPresent
  useFull: true

renovate:
  # Global Renovate config as inline config.json
  # https://docs.renovatebot.com/modules/platform/github/#running-using-a-fine-grained-token
  config: |
    {
      "platform": "github",
      "endpoint": "https://api.github.com",
      "token": "",
      "repositories": ["vladmalynych/devops-edu"],
      "dryRun": false,
      "autodiscover": false,
      "printConfig": true,
      "extends": ["config:base"],
      "automerge": true
    }
  configIsSecret: true
