alertmanager:
  enabled: false

grafana:
  enabled: true

prometheus:
  enabled: true
  prometheusSpec:
    retention: 14d

kubelet:
  enabled: true

kubeControllerManager:
  enabled: false

coreDns:
  enabled: false

kubeDns:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: false
