apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage
  namespace: kargo-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - dev
  promotionTemplate:
    spec:
      vars:
      - name: gitopsRepo
        value: https://github.com/vladmalynych/devops-edu.git
      - name: imageRepo
        value: nginx
      - name: srcPath
        value: ./src
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitopsRepo }}
          checkout:
          - branch: master
            path: ${{ vars.srcPath }}
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ${{ vars.srcPath }}/kargo/argocd/demo-app/demo/environments/${{ ctx.stage }}
          images:
          - image: ${{ vars.imageRepo }}
            tag: ${{ imageFrom(vars.imageRepo).Tag }}
      - uses: git-commit
        as: commit
        config:
          path: ${{ vars.srcPath }}
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ${{ vars.srcPath }}
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-${{ ctx.stage }}
            sources:
            - repoURL: ${{ vars.gitopsRepo }}
              desiredRevision: ${{ outputs.commit.commit }}
