apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo
  namespace: kargo
spec:
  promotionPolicies:
  - stage: dev
    autoPromotionEnabled: true
  - stage: stage
    autoPromotionEnabled: false
  - stage: prod
    autoPromotionEnabled: false
