apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rabbitmq-system

# Install the official operators from release artifacts (pinned) and custom cluster definition
resources:
  - github.com/rabbitmq/cluster-operator/config/default?ref=v2.17.0
  - cluster/cluster.yaml
