apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rabbitmq-system

# Install the official operators from release artifacts (pinned)
resources:
  - https://github.com/rabbitmq/messaging-topology-operator/releases/v1.18.0/download/messaging-topology-operator-with-certmanager.yaml
