## -----------------------------------------------------------------------------
## Shared Object‐Store Configuration (applies to Compactor, BucketWeb, StoreGateway)
## -----------------------------------------------------------------------------
objstoreConfig: |
  type: S3
  config:
    bucket: "thanos"
    endpoint: "localstack.localstack:4566"
    region: "us-east-1"
    insecure: true
    access_key: "test"
    secret_key: "test"

## -----------------------------------------------------------------------------
## Thanos Query & Query Frontend
## -----------------------------------------------------------------------------
query:
  enabled: true
  logLevel: info
  revisionHistoryLimit: 1
  dnsDiscovery:
    enabled: true
    sidecarsService: "kube-prometheus-stack-thanos-discovery"
    sidecarsNamespace: "monitoring"

queryFrontend:
  enabled: true
  logLevel: info
  revisionHistoryLimit: 1

## -----------------------------------------------------------------------------
## Thanos Compactor
## -----------------------------------------------------------------------------
compactor:
  enabled: true
  logLevel: info
  # configuration to decrease number of requests to S3
  # extraFlags: ["--wait-interval=4h", "--compact.cleanup-interval=0s", "--compact.progress-interval=0s"]
  revisionHistoryLimit: 1
  retentionResolutionRaw: 7d
  retentionResolution5m:  14d
  retentionResolution1h:  30d
  persistence:
    enabled: false
    ephemeral: false
    defaultEmptyDir: true

## -----------------------------------------------------------------------------
## Thanos BucketWeb
## -----------------------------------------------------------------------------
bucketweb:
  enabled: true
  logLevel: info
  revisionHistoryLimit: 1

## -----------------------------------------------------------------------------
## Thanos Store Gateway
## -----------------------------------------------------------------------------
storegateway:
  enabled: true
  logLevel: info
  revisionHistoryLimit: 1
  persistence:
    enabled: false
