apiVersion: batch/v1
kind: CronJob
metadata:
  name: krr
  namespace: krr
spec:
  schedule: "0 9 1 * *"  # first day of each month
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: krr
        spec:
          restartPolicy: Never
          serviceAccountName: krr
          containers:
            - name: krr
              image: robustadev/krr:v1.28.0
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: krr-secrets
              command:
                - /bin/sh
                - -c
                - |
                  set -euo pipefail
                  echo "[KRR] Starting analysis..."
                  python krr.py simple \
                    --resource=Deployment \
                    --resource=StatefulSet \
                    --resource=DaemonSet \
                    --fileoutput="krr-report-${CLUSTER_NAME}.csv" \
                    --max-workers=10 \
                    --cpu-min=10 \
                    --mem-min=20 \
                    --cpu-percentile=95 \
                    --memory-buffer-percentage=15 \
                    --history-duration=720 \
                    --timeframe-duration=1 \
                    --use-oomkill-data \
                    --oom-memory-buffer-percentage=25 \
                    --allow-hpa \
                    --formatter=csv \
                    --width=2048 \
                    --logtostderr
                    # --slackoutput="${SLACK_CHANNEL}" \
                    # --slacktitle=":bar_chart: [${CLUSTER_NAME}] - Kubernetes Resource Report" \
                  echo "[KRR] Report successfully generated"
              resources:
                requests:
                  memory: 2Gi
                limits:
                  memory: 2Gi