apiVersion: v1
kind: ServiceAccount
metadata:
  name: krr
  namespace: krr
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krr
rules:
  - apiGroups: ["*"]
    resources:
      - nodes
      - namespaces
      - services
      - daemonsets
      - deployments
      - deployments/scale
      - statefulsets
      - replicasets
      - replicasets/scale
      - replicationcontrollers
      - pods
      - jobs
      - cronjobs
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: krr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: krr
subjects:
  - kind: ServiceAccount
    name: krr
    namespace: krr
