apiVersion: v1
kind: Secret
metadata:
  name: krr-secrets
  namespace: krr
type: Opaque
stringData:
  # SLACK_BOT_TOKEN: 'xoxb-xxxxxxxxxxxxxx'
  # SLACK_CHANNEL: '#krr-reporting'
  CLUSTER_NAME: 'stage'
