apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-phpmyadmin
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: registry-1.docker.io
    chart: bitnamicharts/phpmyadmin
    targetRevision: 18.1.4
    helm:
      releaseName: phpmyadmin
      valueFiles:
      - $values/renovatebot/argocd/demo-phpadmin/helm/values.yaml
  - repoURL: 'https://github.com/vladmalynych/devops-edu.git'
    targetRevision: master
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: phpmyadmin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true