apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-mysql
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: mysql
    targetRevision: "12.2.2"
    helm:
      valueFiles:
        - $helm/values.yaml
  - repoURL: 'https://github.com/vladmalynych/devops-edu.git'
    targetRevision: master
    path: renovatebot/argocd/demo-mysql/helm
    ref: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true