apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-mysql
  namespace: argocd
spec:
  project: default
  sources:
  - chart: bitnamicharts/mysql
    repoURL: registry-1.docker.io
    targetRevision: 9.23.0
    helm:
      releaseName: mysql
      valueFiles:
        - $helm/renovatebot/argocd/demo-mysql/helm/values.yaml
  - repoURL: 'https://github.com/vladmalynych/devops-edu.git'
    targetRevision: master
    ref: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true