apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-test
  namespace: stress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-test
  template:
    metadata:
      labels:
        app: stress-test
    spec:
      containers:
        - name: stress-test
          image: polinux/stress
          command: ["stress"]
          args:
            - "--cpu"
            - "1"
            - "--io"
            - "1"
            - "--vm"
            - "1"
            - "--vm-bytes"
            - "128M"
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
